# Generated by Django 3.0.7 on 2021-08-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('hold', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=6)),
            ],
        ),
    ]
