# Generated by Django 3.0.7 on 2021-08-12 17:21

from django.db import migrations

def populate_account(apps, schema_editor):
    Account = apps.get_model("account", "Account")
    account = Account(id='26c940a1-7228-4ea2-a3bc-e6460b172040', name='Петров Иван Сергеевич', balance = 1700 , hold = 300 , status = 'Open')
    account.save()
    account = Account(id='7badc8f8-65bc-449a-8cde-855234ac63e1', name='Kazitsky Jason', balance = 200, hold = 200 , status = 'Open')
    account.save()
    account = Account(id='5597cc3d-c948-48a0-b711-393edf20d9c0', name='Пархоменко Антон Александрович', balance = 10 , hold = 300 , status = 'Open')
    account.save()
    account = Account(id='867f0924-a917-4711-939b-90b179a96392', name='867f0924-a917-4711-939b-90b179a96392', balance =1000000 , hold = 1 , status =  'Closed')
    account.save()

def clear_account(apps, schema_editor):
    Account = apps.get_model("account", "Account")

    Account.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_account, clear_account),
    ]
